### ISSUE TITLE
2048 tiles litle blurry

### ISSUE THREAD

**Issue by MihinMUD** [TechDudie/minegame#2]
# Game tiles are kinda blurry

I guess it happens because it is a pixel image and browser trying to make it smooth

can use CSS to fix it

```css
image-rendering: pixelated;
```
😁 like the game so much

**Comment by TechDudie** [comment]
Yeah, it’s blurry, I agree. I first used 16x16 images, which was a mistake, because they tiled. So I did some counting and I figured I needed to resize them to 107x107. I did, but it’s still blurry. I’m guessing that if I enlarge them more, they will not fit in the tile, so I just canned it and left it like that.

**Comment by TechDudie** [comment]
Oh, and lemme fix the github-actions

**Comment by TechDudie** [comment]
Anyhow I’ll try it though

**Comment by TechDudie** [comment]
Tbh I have no idea, not a single idea what it looks like on a computer
I do most of my developing with SSH or on my iPad

**Comment by MihinMUD** [comment]
maybe high res images will help
